### ISSUE TITLE
Closures fundamentally broken 

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-gnome/gtk#16]
[original](https://github.com/jeremyletang/rgtk/issues/28).

**Comment by StephanvanSchaik** [comment]
I have a proposition to possibly fix this, the problem however is that it would require some additional wrapping to get it to work. So the current problem with closures seems to be that they are unable to live long enough to actually be called whenever a signal gets triggered. This happens because they get passed to the C interface, but the Rust binding keeps owning them. Eventually, they will get cleaned up from the stack, after the function where they were created at returns. Then, when Glib and GTK+ actually need them, they end up invoking a closure with garbage data.

To fix this, we would have to claim ownership of the closures within the binding, and store them somewhere safe. What I am basically proposing is to keep track of signal mappings for `GObjects` in a `HashMap` or something similar, and add a `dispatch` method to actually invoke the associated callbacks. This would look something like [this](https://gist.github.com/StephanvanSchaik/91f58dad12ebcc24fe91).

Then once this is in place, we can implement callbacks for the actual signals that will in turn use this signal map to dispatch the signals to their respective callbacks. So yes, the unfortunate part, is that we are essentially implementing our own signal system on top of an existing one.

However, if we do it properly, we only have to connect the signals that have to be, i.e. if the a signal is not in use, it should not be in use in the low-level layer either.

Then there should be one final issue, and that is getting the callbacks to be generic enough that they can be used for the different events. This should be doable with traits, but this idea still requires some more polishing.

**Comment by gkoz** [comment]
Owning is not a big issue, we can even let the lib own them like in this example: https://gist.github.com/gkoz/52ae8de5370ba99d9795
BTW I believe the handlers can't generally be `FnMut` because they need to be reentrant.
Supporting different numbers and sets of arguments and converting them between foreign and native types is tough.

**Comment by gkoz** [comment]
Maybe that signal-specific glue will just have to be done by hand similarly to the method calls.

**Comment by StephanvanSchaik** [comment]
I think they can be either `Fn` or `FnMut`, depending on whether you want the changes to the environment to be persistent or not.

**Comment by StephanvanSchaik** [comment]
Hmm, I get what you mean with it being hard. The problem mostly lies in the fact that C uses some assumptions that are rightfully considered unsafe. Like the way Glib works is it keeps track of a what callbacks have been associated with what signal name, i.e. the corresponding callback could be any kind of function pointer (because they can be cast to `void *` or `void (*)()` and to the desired function pointer in C, which is unsafe: since you could connect the wrong kind of callback and accidentally execute functions of which the type signatures do not match).

Unfortunately, this is useful when you want to look up the function to hook up via constructions such as `dlsym`, but I am not sure if there is actually a safe way of doing something similar, It could be possible by using an `enum` with all the possible closures. When dispatching, you can check whether the one stored in the table does match the type signature that is required for the event that is to be dispatched. Similarily, when storing a closure for a certain signal, you could wrap it up in the enum.

Although, even if that works, I am not sure whether it would actually be possible to use a builder à la Glade.

**Comment by StephanvanSchaik** [comment]
I've been looking at your example, and I see how you could have the library own the closure with proper deletion by passing a callback to clean it up. I have to admit, that I still had to read about what `transmute` actually does, and now that I understand that, I also understand why your code works :).

Ownership was one of my concerns because the original code in upstream takes a mutable reference to a closure, instead of actually moving the closure to the function, but that issue is solved with what you are currently doing.

I think it makes sense to implement the signals by hand for the moment being, I am willing to help with that, and then later on, attempt to generalise it in the form of macros.

**Comment by GuillaumeGomez** [comment]
@StephanvanSchaik: That'd be very nice ! Any help is appreciated ^^

**Comment by gkoz** [comment]
> I think they can be either Fn or FnMut, depending on whether you want the changes to the environment to be persistent or not.

It's conceivable that a signal handler can end up causing the same signal to be processed in a recursive manner ([example](http://stackoverflow.com/questions/7941341/why-do-i-get-a-runtime-error-with-two-linked-gtk-toggle-buttons)). I believe such use isn't compatible with `FnMut`, which expects its mutable borrows to be unique.

**Comment by gkoz** [comment]
As there is some momentum for fixing the closures, I'll try to integrate the example from https://github.com/rust-gnome/gtk/issues/16#issuecomment-92160606 into the tree without breaking existing signals support.

**Comment by gkoz** [comment]
There's actually an even stricter constraint to what we can give to the lib. It's `Fn + 'static` i.e. the closure wouldn't be allowed to capture any non-static references at all.
The approach of owning the closures ourselves would be more flexible but it's not clear it'd gain us anything in practice. It could probably be done incrementally afterwards. One more practical problem with that is that `rc::Weak` isn't going to be stable in Rust 1.0.

**Comment by gkoz** [comment]
The proposed solution for review: https://github.com/rust-gnome/gtk/pull/33

**Comment by gkoz** [comment]
The initial implementation has been merged, we need to migrate all of the signals into [this module](https://github.com/rust-gnome/gtk/blob/master/src/signal.rs) now and then remove the old infrastructure.

**Comment by gkoz** [comment]
cc @oakes

**Comment by gkoz** [comment]
So the closures aren't broken any more. They're just not very convenient now... :)
